### ISSUE TITLE
StreamingSound seek on mp3 doesn't seem to work?

### ISSUE THREAD

**Issue by combs** [nwhitehead/swmixer#2]
This module is great! Thank you for making it. 

Here is a minor glitch I've found: Trying a seek to random positions with a StreamingSound mp3, I get the same output each time...

example file:

```
from __future__ import print_function
from time import sleep
from random import randint
import swmixer as swmixer

channels = {}
controllers = {}

swmixer.init(samplerate=22050, chunksize=1024, stereo=True)
swmixer.start()

channels["example"]  = swmixer.StreamingSound("243546__kb7clx__slow-tune-through-40-meters-from-7000-to-7572-3khz-lsb-3khz-filter.mp3")
controllers["example"] = channels["example"].play(volume=1.0, fadein=90000, loops=-1)

theLength = channels["example"].get_length()
thePosition = randint(0,theLength)
print("USING THIS POSITION: ",thePosition)
controllers["example"].set_position(thePosition)
sleep(500)
```

I used [this sound](https://www.freesound.org/people/kb7clx/sounds/243546/) but have seen this with many other files generated with different encoders. using python2.7

Thanks,
Chris

**Comment by combs** [comment]
hmm, this may be related to an ancient version of pymad--turns out I had the apt package for that installed, so it was ignoring pymad 0.9.1 in my /usr/local/. digging some more...

**Comment by combs** [comment]
ahh, seems like pymad > 0.7 is returning bytearrays in a way that swmixer doesn't appreciate.
```
Unhandled exception in thread started by <function f at 0xb6004fb0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/swmixer.py", line 672, in f
    tick()
  File "/usr/local/lib/python2.7/dist-packages/swmixer.py", line 597, in tick
    s = sndevt._get_samples(sz)
  File "/usr/local/lib/python2.7/dist-packages/swmixer.py", line 185, in _get_samples
    z = self.src.get_samples(sz)
  File "/usr/local/lib/python2.7/dist-packages/swmixer.py", line 99, in get_samples
    z = numpy.fromstring(self.buf[:szb], dtype=numpy.int16)
TypeError: argument 1 must be string or read-only buffer, not bytearray

```

**Comment by combs** [comment]
It looks like it broke in pymad 0.9. pymad 0.8.4 is working well in my application.
