### ISSUE TITLE
MP3 support : "TypeError: sequence item 0: expected string, bytearray found"

### ISSUE THREAD

**Issue by raphaelyancey** [nwhitehead/swmixer#3]
I'm getting an error when trying to play an MP3 file.

```
# _swmixer.py
import swmixer
import time
swmixer.init()
swmixer.start()
snd = swmixer.Sound("./audio/1.mp3")
snd.play()
time.sleep(5)
```

```
# $ python _swmixer.py
Traceback (most recent call last):
  File "_swmixer.py", line 14, in <module>
    snd = swmixer.Sound("./audio/1.mp3")
  File "/[...]/lib/python2.7/site-packages/swmixer.py", line 310, in __init__
    self.data = numpy.fromstring(''.join(data), dtype=numpy.int16)
TypeError: sequence item 0: expected string, bytearray found
```

```
# $ pip list
numpy (1.13.3)
pip (9.0.1)
PyAudio (0.2.11)
pymad (0.10)
setuptools (36.5.0)
SWMixer (0.1.4)
wheel (0.30.0)
```

Seems like [`mf.read()`](https://github.com/nwhitehead/swmixer/blob/master/swmixer.py#L307) returns a bytearray rather than an expected string?

**Comment by raphaelyancey** [comment]
@nwhitehead Thanks. Is it your move to update the pypi package?
